name: Actualizar Carreras Diariamente

# Se ejecuta cada día a las 06:00 AM UTC
on:
  schedule:
    - cron: '0 6 * * *'
  # También permite ejecutarlo manualmente desde la web de GitHub
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    # Solo necesitamos leer el código, no escribir
    permissions:
      contents: read

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Ejecutar Scrapers y Fusión
        env:
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
        run: python main.py
